version: '2.0'
services:
  creport:
    image: creport:1.0.1
    volumes:
       - "./creport/conf:/go/conf"
       - "./creport/logs:/go/logs"
    container_name: creport
    ports:
      - 28098:28098
    command: ["/go/flowreport", "-conf" , "/go/conf/"]
  cginstanceagent:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./cginstanceagent:/home/stubby4j/data"
    container_name: cginstanceagent
    ports:
      - 8000:8000
    environment:
      YAML_CONFIG: stub.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 8000
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
  gsm:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./gsm:/home/stubby4j/data"
    container_name: gsm
    ports:
      - 51777:51777
    environment:
      YAML_CONFIG: stub.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 51777
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
  localmachine:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./localmachine:/home/stubby4j/data"
    container_name: localmachine
    ports:
      - 51888:51888
    environment:
      YAML_CONFIG: stub.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 51888
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
  cephAgent:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./cephAgent:/home/stubby4j/data"
    container_name: cephAgent
    ports:
      - 8888:8888
    environment:
      YAML_CONFIG: stub.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 8888
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
  unionAcl:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./unionAcl:/home/stubby4j/data"
    container_name: unionAcl
    ports:
      - 8889:8889
    environment:
      YAML_CONFIG: stub.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 8889
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"